CREATE TABLE departments (id SERIAL PRIMARY KEY, name VARCHAR(30) NOT NULL UNIQUE);

CREATE TABLE employers (id SERIAL PRIMARY KEY, department_id INT REFERENCES departments(id) ON DELETE CASCADE, name VARCHAR(20), email VARCHAR(20) NOT NULL UNIQUE, birthday DATE, rank INT);